# Open a viewer
/vis/open
# Disable auto refresh and quieten vis messages whilst scene and
# trajectories are established:
/vis/viewer/set/autoRefresh false

# Draw geometry:
/vis/drawVolume

# Specify view angle:
/vis/viewer/set/viewpointThetaPhi 0. 0.

# Specify zoom value:
#/vis/viewer/zoom 2.

# Specify style (surface, wireframe, auxiliary edges,...)
#/vis/viewer/set/style wireframe
#/vis/viewer/set/auxiliaryEdge true
#/vis/viewer/set/lineSegmentsPerCircle 100

# Draw coordinate axes:
#/vis/scene/add/axes 0 0 0 1 mm

# Draw smooth trajectories at end of event, showing trajectory points
# as markers 2 pixels wide:
/vis/scene/add/trajectories
#/vis/scene/add/trajectories smooth #adds trajectory points
#/vis/modeling/trajectories/create/drawByParticleID
#/vis/modeling/trajectories/drawByParticleID-0/set e- blue
#/vis/modeling/trajectories/create/drawByCharge
#/vis/modeling/trajectories/drawByCharge-0/default/setDrawStepPts true
#/vis/modeling/trajectories/drawByCharge-0/default/setStepPtsSize 1
# (if too many tracks cause core dump => /tracking/storeTrajectory 0)

# Draw hits at end of event:
#/vis/scene/add/hits

#To draw all but some particles
/vis/filtering/trajectories/create/particleFilter
/vis/filtering/trajectories/particleFilter-0/add anti_nu_e
/vis/filtering/trajectories/particleFilter-0/add anti_nu_mu
/vis/filtering/trajectories/particleFilter-0/add nu_e
/vis/filtering/trajectories/particleFilter-0/add nu_mu
/vis/filtering/trajectories/particleFilter-0/add e+
# To invert the above, drawing all particles, except those selected
/vis/filtering/trajectories/particleFilter-0/invert true

# To select colour by particle ID:
/vis/modeling/trajectories/create/drawByParticleID
/vis/modeling/trajectories/drawByParticleID-0/default/setDrawStepPts true
/vis/modeling/trajectories/drawByParticleID-0/set e- blue
/vis/modeling/trajectories/drawByParticleID-0/set e+ red
/vis/modeling/trajectories/drawByParticleID-0/set mu- green
/vis/modeling/trajectories/drawByParticleID-0/set mu+ yellow
/vis/modeling/trajectories/drawByParticleID-0/set gamma gray
/vis/modeling/trajectories/drawByParticleID-0/set opticalphoton orange

# To superimpose all of the events from a given run:
/vis/scene/endOfEventAction accumulate
#
# Re-establish auto refreshing and verbosity:
/vis/viewer/set/autoRefresh true
#
# For file-based drivers, use this to create an empty detector view:
#/vis/viewer/flush
